---
title: Therese Plath Real Estate
timezone: Australia/Brisbane
collections:
  general:
    title: General
    output: false
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- README.markdown
- package.json
- gulp.js
- gulpfile.js
- node_modules
