---
title: Therese Plath Real Estate
url: http://thereseplathre.siteleaf.net
timezone: Australia/Brisbane
collections:
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
  uploads:
    title: Uploads
    output: true
  estimate:
    title: estimate
    output: true
exclude:
- README.markdown
- package.json
- gulp.js
- gulpfile.js
- node_modules
