---
title: Therese Plath Real Estate
url: http://thereseplathre.siteleaf.net
timezone: Australia/Brisbane
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
