---
title: Therese Plath Real Estate
url: http://thereseplathre.siteleaf.net
timezone: Australia/Brisbane
exclude: [README.markdown, package.json, gulp.js, gulpfile.js, node_modules]
collections:
    posts:
        title: Posts
        output: true
    uploads:
        title: Uploads
        output: true
    profiles:
        title: Profiles
        output: false
