---
title: Therese Plath Real Estate
url: http://thereseplath.com.au
timezone: Brisbane
permalink: pretty
description: 
keywords: 
therese-plath-youtube: u4SfjE52sQo?autoplay=1&modestbranding=1&showinfo=0&rel=0
google-analytics: UA-76097257-1
collections:
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - fenced_code_blocks
  - lax_spacing
  - strikethrough
  - superscript
  - tables
  - footnotes
  - highlight
