---
title: Therese Plath Real Estate
timezone: Australia/Brisbane
collections:
  blog:
    title: Posts
    output: true
  postsx:
    title: Posts
    output: true
  postsy:
    title: Posts
    output: true
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
  tags:
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- README.markdown
- package.json
- gulp.js
- gulpfile.js
- node_modules
